# Generated by Django 4.2.6 on 2024-01-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('gender', models.CharField(max_length=254)),
                ('registerno', models.BigIntegerField()),
                ('idno', models.CharField(max_length=254)),
                ('aadharno', models.BigIntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
