# Generated by Django 4.2.6 on 2024-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
    ]
