# Generated by Django 4.2.6 on 2024-03-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(max_length=254),
        ),
    ]
