# Generated by Django 4.2.6 on 2024-03-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_profile_alter_member_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.IntegerField(),
        ),
    ]
