# Generated by Django 4.2.6 on 2024-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='destinaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('gender', models.CharField(max_length=254)),
                ('registerno', models.BigIntegerField()),
                ('idno', models.CharField(max_length=254)),
                ('aadharno', models.BigIntegerField()),
                ('year', models.CharField(max_length=254)),
                ('profile', models.ImageField(upload_to='picture/')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.BigIntegerField(),
        ),
    ]
