# Generated by Django 4.2.6 on 2024-03-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_od_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='od_form',
            name='Duration',
            field=models.BigIntegerField(),
        ),
    ]
