# Generated by Django 4.2.6 on 2024-03-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_od_form_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='od_form',
            old_name='Department_name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='od_form',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='od_form',
            old_name='Reason',
            new_name='reason',
        ),
    ]
