# Generated by Django 5.1.4 on 2025-02-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_profile_destinaton_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='profile',
            new_name='image',
        ),
    ]
